autis/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("allauth.urls")),
    path("", include("pages.urls")),
    # path("user/", include("accounts.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

car_rental/car_rental/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("rentalApp.urls")),
]

car_rental/rentalApp/urls.py
from django.urls import path

from . import views

app_name = "rentalApp"
urlpatterns = [
    path("", views.to_home, name="to_home"),
    path("home/", views.home, name="home"),
    # path("rent/", views.rent, name="rent"),
    path("rent/", views.CarReservationView.as_view(), name="rent"),
    path("contact/", views.contact, name="contact"),  # type: ignore
    path("contact/send/", views.send, name="send"),  # type: ignore
]

urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("profile/", views.user_profile, name="user_profile"),
    path("confirm-email/", views.signup_confirmation, name="signup_confirmation"),
]

car_rental/rentalApp/models.py
from django.db import models


# Create your models here.
class RentalLocation(models.Model):
    street = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=100)
    city = models.CharField(max_length=100)

    @property
    def full_address(self):
        return f"{self.street} {self.postal_code} {self.city}"

    def __str__(self):
        return self.full_address


class RentalPeriod(models.Model):
    start_date = models.DateField()
    start_time = models.TimeField()
    end_date = models.DateField()
    end_time = models.TimeField()

    @property
    def full_period(self):
        return f"{self.start_date} {self.start_time} {self.end_date} {self.end_time}"

    def __str__(self):
        return self.full_period


# class RentalAddOn(models.Model):
#     choice = models.CharField(max_length=100)
#
#     def __str__(self):
#         return self.choice

class RentalPersonalDetails(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=100)
    pesel = models.CharField(max_length=100)
    driving_licence = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.email} {self.phone} {self.pesel} {self.driving_licence}"


class RentalPersonalAddress(models.Model):
    personal_street = models.CharField(max_length=100)
    personal_house_number = models.CharField(max_length=100)
    personal_postal_code = models.CharField(max_length=100)
    personal_city = models.CharField(max_length=100)
    personal_country = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.personal_street}, {self.personal_house_number} {self.personal_city}, {self.personal_country}"

car_rental/rentalApp/forms.py
from django import forms
from .models import RentalLocation, RentalPeriod, RentalPersonalDetails, RentalPersonalAddress


class ContactForm(forms.Form):
    firstname = forms.CharField(
        label="Imię",
        error_messages={
            "required": "To pole jest wymagane.",
        },
        widget=forms.TextInput(attrs={"class": "form-control"}),
        # required=False,
    )
    lastname = forms.CharField(
        label="Nazwisko",
        error_messages={"required": "To pole jest wymagane."},
        widget=forms.TextInput(attrs={"class": "form-control"}),
        # required=False,
    )
    comment = forms.CharField(
        label="Wiadomość",
        widget=forms.Textarea(attrs={"class": "form-control"}),
        error_messages={"required": "To pole jest wymagane."},
        # required=False,
    )
    email_address = forms.EmailField(
        label="Adres Email",
        error_messages={"required": "Niepoprawny adres email."},
        widget=forms.EmailInput(attrs={"class": "form-control"}),
        # required=False,
    )


class RentalLocationForm(forms.ModelForm):
    class Meta:
        model = RentalLocation
        fields = ('street', 'postal_code', 'city')


class RentalPeriodForm(forms.ModelForm):
    class Meta:
        model = RentalPeriod
        fields = ('start_date', 'start_time', 'end_date', 'end_time')


# class RentalAddOnForm(forms.Form):
#     class Meta:
#         ADDON_CHOICES = [
#             ('wyjazd_za_granice', 'Wyjazd za granicę'),
#             ('fotelik_dzieciecy', 'Fotelik dziecięcy'),
#             ('dodatkowe_ubezpieczenie', 'Dodatkowe ubezpieczenie'),
#         ]
#         model = RentalAddOn
#         addons = forms.MultipleChoiceField(
#             choices=ADDON_CHOICES,
#             widget=forms.CheckboxSelectMultiple,
#             required=False
#         )


class RentalPersonalDetailsForm(forms.ModelForm):
    class Meta:
        model = RentalPersonalDetails
        fields = ('first_name', 'last_name', 'email', 'phone', 'pesel', 'driving_licence')

class RentalPersonalAddressForm(forms.ModelForm):
    class Meta:
        model = RentalPersonalAddress
        fields = ('personal_street', 'personal_house_number', 'personal_postal_code', 'personal_city', 'personal_country')

car_rental/rentalApp/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from .forms import ContactForm, RentalLocationForm, RentalPeriodForm, RentalPersonalDetailsForm, RentalPersonalAddressForm
from formtools.wizard.views import SessionWizardView


# Create your views here.
def to_home(request):
    return HttpResponseRedirect(reverse("rentalApp:home"))


def home(request):
    return render(
        request,
        "rentalApp/home.html",
    )


def rent(request):
    return render(
        request,
        "rentalApp/rent.html",
    )


def contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data  # Storing Cleaned Data
            return render(
                request,
                "rentalApp/contact.html",
                {
                    "message": data,
                },
            )
        else:
            pass  # Handle Errors In Views
    else:
        form = ContactForm()  # Client Side Form Validation

    return render(
        request,
        "rentalApp/contact.html",
        {
            "form": form,
        },
    )


def send(request):
    if request.method == "POST":
        firstname = request.POST.get("firstname")
        lastname = request.POST.get("lastname")
        comment = request.POST.get("comment")
        email_address = request.POST.get("email_address")
        return render(
            request,
            "rentalApp/send.html",
            {
                "firstname": firstname,
                "lastname": lastname,
                "comment": comment,
                "email_address": email_address,
            },
        )
    if request.method == "GET":
        return HttpResponseRedirect(reverse("rentalApp:contact"))


class CarReservationView(SessionWizardView):
    form_list = [RentalLocationForm, RentalPeriodForm, RentalPersonalDetailsForm, RentalPersonalAddressForm]
    template_name = 'rentalApp/rent.html'

    def done(self, form_list, **kwargs):
        return HttpResponse("Form submitted!")

car_rental/rentalApp/templates/rentalApp/contact.html
{% extends "rentalApp/home.html" %}
{% block title %}
    <title>contact</title>
{% endblock title %}
{% block switch-link %}
<li class="nav-item px-2">
    <a class="nav-link center-link" href="{% url "rentalApp:home" %}">Strona główna</a>
</li>
<li class="nav-item px-2">
    <a class="nav-link center-link" href="{% url "rentalApp:rent" %}">Zarezerwuj samochód</a>
</li>
<li class="nav-item px-2">
    <a class="nav-link center-link switch-link" href="{% url "rentalApp:contact" %}">Kontakt</a>
</li>
{% endblock switch-link %}
{% block content-section %}
<h2>Skontaktuj się z nami</h2>
<p class="pb-4">O czym chciałbyś nam powiedzieć?</p>
<div class="row">
    <div class="col-12 col-lg-6 d-flex flex-column flex-lg-row align-items-center pe-lg-5">
        <div class="form-wrapper w-100">
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-success btn-form">Wyślij</button>
            </form>
        </div>
    </div>
    <div class="col-12 col-lg-6 ps-lg-5">
        <h2 class="pt-4 pt-lg-0">Wypełnij formularz</h2>
        <p>Jeżeli masz jakiekolwiek pytania dotyczące naszej oferty wynajmu samochodów, chcesz uzyskać dodatkowe informacje na temat dostępnych pojazdów lub potrzebujesz wsparcia przy rezerwacji, jesteśmy tutaj, aby Ci pomóc. Prosimy o wypełnienie poniższego formularza kontaktowego, a nasz zespół obsługi klienta skontaktuje się z Tobą tak szybko, jak to możliwe.
        <p>Aby ułatwić nam odpowiedź na Twoje pytania, prosimy o podanie jak najwięcej szczegółów w formularzu kontaktowym. Wypełnij wszystkie wymagane pola, a my postaramy się odpowiedzieć na Twoje zapytanie w możliwie najkrótszym czasie.</p>
    </div>
</div>
<div class="spacer"></div>
{% endblock content-section %}
{% block footer-absolute %}
<footer class="footer text-white text-center py-3">
{% endblock footer-absolute %}

car_rental/rentalApp/templates/rentalApp/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "rentalApp/base.css" %}">
    {% block title %}
    <title>home</title>
    {% endblock title %}

    {% block wizard %}
        {{ wizard.form.media }}
    {% endblock wizard %}

</head>
<body>
    <section class="nav-section">
        <nav class="navbar navbar-light navbar-expand-md bg-light">
            <div class="container-fluid nav-wrapper">
                <div class="lr-spacing">
                    <a class="navbar-brand" href="{% url "rentalApp:home" %}">Panek</a>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasNavbarLabel"><a class="navbar-brand" href="{% url "rentalApp:home" %}">Panek</a></h5>
                        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body d-flex flex-column flex-md-row align-items-center">
                        <ul class="navbar-nav justify-content-end flex-grow-1">
                            <div class="box d-flex flex-column flex-md-row align-items-center" style="margin:0 auto;">
                                {% block switch-link %}
                                <li class="nav-item px-2">
                                    <a class="nav-link center-link switch-link" href="{% url "rentalApp:home" %}">Strona główna</a>
                                </li>
                                <li class="nav-item px-2">
                                    <a class="nav-link center-link" href="{% url "rentalApp:rent" %}">Zarezerwuj samochód</a>
                                </li>
                                <li class="nav-item px-2">
                                    <a class="nav-link center-link" href="{% url "rentalApp:contact" %}">Kontakt</a>
                                </li>
                                {% endblock switch-link %}
                            </div>
                        </ul>
                        <div class="offcanvas-body py-0">
                            <ul class="navbar-nav lr-spacing justify-content-end flex-grow-1">
                                <div class="d-flex flex-column flex-md-row align-items-center justiy-content-center">
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">Login</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="btn btn-success btn-signup" href="#" role="button">Signup</a>
                                    </li>
                                </div>
                            </ul>
                        </div>
                    </div>
                    <div class="offcanvas-header offcanvas-header-bottom">
                    </div>
                </div>
            </div>
        </nav>
    </section>
    <section class="hero-section">
        <div class="hero-container container-fluid px-0 d-flex justify-content-center">
            <img class="img-fluid hero-image" src="{% static 'rentalApp/hero.jpg' %}" alt="road between trees">
            <div class="hero-text">
                <h1>Stay Creative</h1>
                <p>Ride free again</p>
            </div>
            <div class="hero-bg">
            </div>
        </div>
    </section>
    <section class="content-section">
        <div class="content-wrapper container-fluid">
            <div class="spacer"></div>
            {% block content-section %}
            <h2>Oferta</h2>
            {% endblock content-section %}
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

car_rental/rentalApp/templates/rentalApp/rent.html
{% extends "rentalApp/home.html" %}
{% load i18n %}


{% block title %}
    <title>rent</title>
{% endblock title %}
{% block switch-link %}
<li class="nav-item px-2">
    <a class="nav-link center-link" href="{% url "rentalApp:home" %}">Strona główna</a>
</li>
<li class="nav-item px-2">
    <a class="nav-link center-link switch-link" href="{% url "rentalApp:rent" %}">Zarezerwuj samochód</a>
</li>
<li class="nav-item px-2">
    <a class="nav-link center-link" href="{% url "rentalApp:contact" %}">Kontakt</a>
</li>
{% endblock switch-link %}
{% block content-section %}
    <h2>Rezerwacja</h2>
    <p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
    <form action="" method="post">{% csrf_token %}
    <table>
    {{ wizard.management_form }}
    {% if wizard.form.forms %}
        {{ wizard.form.management_form }}
        {% for form in wizard.form.forms %}
            {{ form.as_table }}
        {% endfor %}
    {% else %}
        {{ wizard.form }}
    {% endif %}
    </table>
    {% if wizard.steps.prev %}
    <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">{% translate "first step" %}</button>
    <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">{% translate "prev step" %}</button>
    {% endif %}
    <input type="submit" value="{% translate "submit" %}"/>
    </form>
{% endblock content-section %}

car_rental/rentalApp/templates/rentalApp/send.html
{% extends "rentalApp/home.html" %}
{% block title %}
    <title>send</title>
{% endblock title %}
{% block switch-link %}
<li class="nav-item px-2">
    <a class="nav-link center-link" href="{% url "rentalApp:home" %}">Strona główna</a>
</li>
<li class="nav-item px-2">
    <a class="nav-link center-link" href="{% url "rentalApp:rent" %}">Zarezerwuj samochód</a>
</li>
<li class="nav-item px-2">
    <a class="nav-link center-link" href="{% url "rentalApp:contact" %}">Kontakt</a>
</li>
{% endblock switch-link %}
{% block content-section %}
    <h2>Dziękujemy</h2>
    <p>Formularz kontaktowy został przesłany.</p>
{% endblock content-section %}